AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  LeadDeveloperChallenge

Globals:
  Function:
    Timeout: 120
    MemorySize: 1024
    Runtime: python3.9
    Tracing: Active
  Api:
    TracingEnabled: true

Resources:
  Firesat23:
    Type: AWS::Serverless::Function 
    Properties:
      Handler: app.lambda_handler
      CodeUri: Firesat23/
      Architectures:
      - x86_64
      Tracing: Active
  
  FireSegmentationApi:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      CodeUri: FireSegmentationAPI/
      Architectures:
      - x86_64
      Tracing: Active
      Events:
        PostSegmentation:
          Type: Api
          Properties:
            Path: /segmentation
            Method: post

  #ApplicationResourceGroup:
  #  Type: AWS::ResourceGroups::Group
  #  Properties:
  #    Name:
  #      Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
  #    ResourceQuery:
  #      Type: CLOUDFORMATION_STACK_1_0
  #ApplicationInsightsMonitoring:
  #  Type: AWS::ApplicationInsights::Application
  #  Properties:
  #    ResourceGroupName:
  #      Ref: ApplicationResourceGroup
  #    AutoConfigurationEnabled: 'true'